services:
  quiz-api:
    build:
      target: development
    image: quiz-api-development
    container_name: quiz-api-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - quiz
    environment:
      REDIS_HOST: redis

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:

networks:
  quiz:
    driver: bridge
    name: quiz
