services:
  quiz-api:
    build:
      target: development
    image: quiz-api-development
    container_name: quiz-api-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - quiz

networks:
  quiz:
    driver: bridge
    name: quiz
